version: "3.9"

services:
  linkedin-bot-api:
    #build: .
    image: busshi/linkedin_bot_api:latest
    pull_policy: always

    container_name: linkedin_bot_api

    env_file:
      - ./app/.env

    entrypoint: yarn run prod

    restart: on-failure:5
